# Generated by Django 3.1.7 on 2021-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Example Title', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('account_id', 'title')},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='version',
        ),
    ]
