# Generated by Django 3.1.7 on 2021-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocket', '0002_auto_20210405_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'BUY'), (1, 'SELL')], default=0),
            preserve_default=False,
        ),
    ]
