# Generated by Django 3.1.7 on 2021-05-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocket', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_record', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocket.portfolio')),
            ],
            options={
                'order_with_respect_to': 'portfolio',
            },
        ),
    ]
