# Generated by Django 3.1.7 on 2021-06-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocket', '0004_auto_20210528_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='time_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('portfolio', 'time_record')},
        ),
    ]
